name: Celana Dalam

on:
  push:
    branches: ["celana-dalam"]
  # pull_request:
  #   branches: ["main"]
  workflow_dispatch:

jobs:
  angular:
    name: Angular Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4
      - name: Setup Node.js $
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build -c production
      - name: Cek isinya apa aja
        run: ls -la dist/
      - name: Copy Files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_ADDRESS }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          source: "dist/fe/browser/*"
          target: "/var/www/lokakarya-fe"
          strip_components: 3

      - name: Execute Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_ADDRESS }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            echo "Deployment completed at $(date)"
            sudo systemctl restart nginx
